export * as accountController from "./account";
export * as dashboardController from "./dashboard";
export * as postsController from "./posts";
export * as commentsController from "./comments";
export * as repliesController from "./replies";
export * as followersController from "./followers";
export * as friendsController from "./friends";
export * as friendRequestController from "./friend-request";
export * as galleryController from "./gallery";